### ISSUE TITLE
map_image functions pOut write pointers should increment in larger steps

### ISSUE THREAD

**Issue by mzeilfelder** [exoticorn/exoquant#2]
exq_map_image and exq_map_image_dither  both increase pOut only by a single byte per pixel. Should either be 4 bytes or pOut would need some other type than unsigned char like exq_color instead.
Currently out images are broken (overwriting top-quarter of the image with red-values).

**Comment by exoticorn** [comment]
Yes, the output image is supposed to be one byte per pixel. IE. each pixel is a one byte index (0-255) into the palette.

In general, though, this library is quite old and a bit on the slow side. You are of course welcome to use it, but should at least also consider [libimagequant](https://pngquant.org/lib/) which produces similar quality images at much better performance.

**Comment by mzeilfelder** [comment]
Ah, OK, output-format is different from input format. That also explains the somewhat strange results I got now :-) Thanks for clarifying.
